database:
  type: sqlite
  sqlite:
    path: investment.db
  postgresql:
    host: localhost
    port: 5432
    database: investment
    user: postgres
    password: ''
    sslmode: prefer
cookie:
  expiry_days: 30
  key: investment_tracker_cookie_key_change_me
  name: investment_tracker_auth
credentials:
  usernames:
    nihilo:
      email: 1871704893@qq.com
      first_name: nihilo
      last_name: ''
      password: $2b$12$q19iMPoCICzyXiMPynLbDODTC6KHTFczJ663WTb7nuYbztURVUYNy
      password_hint: nihilo_lu
      roles:
      - admin
      failed_login_attempts: 0
      logged_in: false
      api_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5paGlsbyIsImlhdCI6MTc3MDYzODg1Nn0.HdDktUb1WBg21sppk1j2BDbu6VxnQYndzAVueO74tqg
pre-authorized:
  emails: []
pwa:
  name: 投资追踪器
  short_name: 投资追踪
  description: 投资组合追踪与收益分析工具
  theme_color: "#E8A317"
  background_color: "#ffffff"
  display: standalone
  icon_192: /frontend/icons/icon-192.png
  icon_512: /frontend/icons/icon-512.png
